### ISSUE TITLE
Add 'requirements.txt' file

### ISSUE THREAD

**Issue by masiarek** [Equal-Vote/starpy#20]
- pip install starpy 

ERROR: Could not find a version that satisfies the requirement starpy (from versions: none)
ERROR: No matching distribution found for starpy

Proposed 'requirements.txt' file:

- numpy>=1.23.2
- pandas>=1.4.3
- pytest>=7.1.2

Or, we should use 'poetry'?

https://install.python-poetry.org

curl -sSL https://install.python-poetry.org | python3 -

**Comment by penyuan** [comment]
I suggest sticking as much as possible to vanilla Python, hence `requirements.txt`. IMO this repository should be kept relatively simple as a reference implementation, while the bells and whistles can go to [star-server](https://github.com/Equal-Vote/star-server).

**Comment by mikefranze** [comment]
starpy isn't a published package yet so you can't install it with pip. Once we're happy with the current version we can publish it. https://realpython.com/pypi-publish-python-package/

This will include creating a list of dependencies. For the purposes of a python package though we wouldn't include pytest and the test files. And while we do want to limit the dependencies, our current ones like numpy and pandas are so common it shouldn't be an issue and they help us avoid reinventing a lot of wheels.

**Comment by mikefranze** [comment]
Also, I think we do want this to be both a reference and a usable library. People need to know about the nuts and bolts when writing their implementation but it also has to be readable. Plus star server is only JavaScript.

**Comment by ArendPeter** [comment]
requirements.txt sounds good for now, but we might want to switch to poetry later

It's been a while since I looked into it, but I vaguely remember that poetry had a lot of benefits over the requirements approach when it comes to packaging
